# This is a basic workflow to help you get started with Actions

name: Afficher un message à chaque push ou pull request 
on:

  push:
    branches: [ "main", "feature/about" ]
  pull_request:
    branches: [ "main", "feature/about" ]


jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: affiche un message en console
        run: echo "Une modification a été poussée ou une PR a été ouverte sur $(git branch --show-current)"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
